# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "ehci_pci"
    "xhci_pci_renesas"
    "xhci_pci"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-28c9b798-ce05-4416-a494-91446f1de464";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-28c9b798-ce05-4416-a494-91446f1de464".device =
    "/dev/disk/by-uuid/28c9b798-ce05-4416-a494-91446f1de464";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/AF14-93E6";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  boot.initrd.luks.devices."luks-fc959d06-204f-4e17-9735-0bb21e38223e".device = "/dev/disk/by-uuid/fc959d06-204f-4e17-9735-0bb21e38223e";
  swapDevices = [
    { device = "/dev/mapper/luks-fc959d06-204f-4e17-9735-0bb21e38223e"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
