# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "ehci_pci"
    "xhci_pci_renesas"
    "xhci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-16543bd4-277b-4eeb-abaa-3cea8a28752e";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-16543bd4-277b-4eeb-abaa-3cea8a28752e".device =
    "/dev/disk/by-uuid/16543bd4-277b-4eeb-abaa-3cea8a28752e";

  fileSystems."/home" = {
    device = "/dev/mapper/luks-16543bd4-277b-4eeb-abaa-3cea8a28752e";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-16543bd4-277b-4eeb-abaa-3cea8a28752e";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E7C1-B05B";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-680bcfa9-eab9-43f9-a969-3ec08e88c72e"; }
  ];

  boot.initrd.luks.devices."luks-680bcfa9-eab9-43f9-a969-3ec08e88c72e".device =
    "/dev/disk/by-uuid/680bcfa9-eab9-43f9-a969-3ec08e88c72e";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
