# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-1170b283-9e45-4b6b-aa7f-627bfb29d217";
    fsType = "ext4";
  };
  boot.initrd.luks.devices."luks-66d77a9f-1923-4b3d-b33a-3136e8c655ea".device =
    "/dev/disk/by-uuid/66d77a9f-1923-4b3d-b33a-3136e8c655ea";
  boot.initrd.luks.devices."luks-1170b283-9e45-4b6b-aa7f-627bfb29d217".device =
    "/dev/disk/by-uuid/1170b283-9e45-4b6b-aa7f-627bfb29d217";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F047-1AFB";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-66d77a9f-1923-4b3d-b33a-3136e8c655ea"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
