# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "https://github.com/bezmuth/glitch-soc-prop-lol.git";
    rev = "0751ef7e29edda37973cb7d27764c007dc9d1d9c";
    hash = "sha256-cVBhn9vBjfxzrL0d5mqRzk34OhFp30PP8WSS0mGBvYs=";
  };
in applyPatches {
  inherit src;
  patches = [];
}
