# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "https://github.com/bezmuth/glitch-soc-prop-lol.git";
    rev = "0751ef7e29edda37973cb7d27764c007dc9d1d9c";
    sha256 = "1ah34pc6v4qkld16393wzid8l0pyc81w2lzh1hk9r3anncpp87dx";
  };
in applyPatches {
  inherit src;
  patches = [];
}
